version: '3.5'

services:

    kadeck:
        image: xeotek/kadeck:4.3.3
        container_name: kadeck
        ports:
          - "80:80"
        environment:
          xeotek_kadeck_free: "email@gmail.com"
          xeotek_kadeck_port: "80"
        networks:
            - f-networks

    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper-container
        networks:
            - f-networks

    kafka:
        image: wurstmeister/kafka:latest
        container_name: kafka-container
        ports:
            - "9094:9094"
        environment:
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9094
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CREATE_TOPICS: "topic1:10:1"
        depends_on:
            - zookeeper
        networks:
            - f-networks

    
volumes:
  mongodb-data:

networks:
    f-networks:
        external: true
